version: "3.8"

networks:
  backend:
    name: backend

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocknews
    ports:
      - 5432:5432
    volumes:
      - ../persistence/sql/seed.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  stocknews:
    restart: always
    environment:
      # Prevent Java from bloating
      JAVA_OPTS: "-Xmx512m"
    image: stocknews
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      # Provide your configuration file
      - ./app.conf:/app.conf
    networks:
      - backend
